In [2]:
# Length of a vector
import numpy as np
def computeVectorLength(vector):
  len_of_vector = np.linalg.norm(vector)

  return len_of_vector
vector = np.array([-2, 4, 9, 21])
result = computeVectorLength([vector])
print(round(result,2))

23.28


In [14]:
# Dot product/Multiplying a vector/matrix by a matrix
def computeDotProduct(a, b):
  result = np.dot(a, b)

  return result
v1 = np.array([0, 2])
v2 = np.array([[-1, 1, 1, 1], [0, -4, 9, 0]])
result = computeDotProduct(v1, v2)

print(result) #Cách 1
print(v1.dot(v2)) #Cách 2: dot() chỉ dùng cho tích vô hướng và phép nhân ma trận.
print(v1@v2) #Cách 3: @ có thể được sử dụng cho nhiều loại phép toán khác ngoài NumPy, miễn là các đối tượng định nghĩa phương thức __matmul__.

[ 0 -8 18  0]
[ 0 -8 18  0]
[ 0 -8 18  0]


In [16]:
m1 = np.eye(3)
print(m1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Tham số 'F' và 'C' trong hàm reshape của NumPy đề cập đến thứ tự bộ nhớ (memory order) hoặc thứ tự lưu trữ (storage order) của mảng. Chúng xác định cách các phần tử của mảng được đọc khi thực hiện reshape.

'C' order (row-major): 'C' là viết tắt của "C-style" hoặc "C-contiguous".
Đây là thứ tự mặc định trong NumPy.
Trong thứ tự này, các phần tử được đọc và ghi theo hàng (từ trái sang phải, từ trên xuống dưới).
Phù hợp với cách lưu trữ mảng trong ngôn ngữ lập trình C.


'F' order (column-major). 'F' là viết tắt của "Fortran-style" hoặc "Fortran-contiguous".
Trong thứ tự này, các phần tử được đọc và ghi theo cột (từ trên xuống, từ trái sang phải).
Phù hợp với cách lưu trữ mảng trong ngôn ngữ lập trình Fortran.

In [23]:
m1 = np.array([[1, 2], [3, 4]])
m1 = np.reshape(m1,(4,1), "F")
print(m1)

[[1]
 [3]
 [2]
 [4]]


In [24]:
# Matrix inverse
def inverse_matrix(matrix):
  result = np.linalg.inv(matrix)
  return result
m1 = np.array([[-2, 6], [8, -4]])
result = inverse_matrix(m1)
print(result)

[[0.1  0.15]
 [0.2  0.05]]


In [25]:
# Eigenvector and eigenvalue
def compute_eigenvalues_eigenvectors(matrix):
  eigenvalues, eigenvectors = np.linalg.eig(matrix)
  return eigenvalues,eigenvectors
matrix = np.array([[0.9, 0.2], [0.1, 0.8]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(matrix)
print(eigenvectors)

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [26]:
# Cosine Similarity
import numpy as np
from numpy import dot
from numpy.linalg import norm

def compute_cosine(v1, v2):
  cos_sim = computeDotProduct(v1,v2) / (computeVectorLength(v1)*computeVectorLength(v2))

  return cos_sim
x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])
result = compute_cosine(x,y)
print(round(result, 3))

0.577
